### PR TITLE
adds range arg to clear method on GoogleSpreadsheetWorksheet

### PR DESCRIPTION
**Pull request by brianecook**
🙏🏻

### CODE REVIEW

**Comment by brianecook** [comment]
Or just anything that would make it so that I can clear all rows except the 1st row, which is a header that allows the columns to be sorted based on their data.

image

**Comment by theoephraim** [comment]
This looks like it could be useful regardless, but I agree a shortcut for clearing all rows but not the header may _also_ make sense.

**Comment by theoephraim** [comment]
@brianecook I'll try to get this merged in soon, but I'll want to update the docs and tests too first. If you have time and can add those things, it'll get merged in faster.

Cheers and thanks!

**Comment by zachrdz** [comment]
I would also love this feature! I've been using clear() to be able to quickly remove all rows, but since you always need a header before inserting new rows, I have had to reinsert the header before I insert data rows every time. In my use case I am simply deleting all the rows of data and replacing it with new data, so I would like the header to be preserved along with styling and freezing the header for scrolling. By having to delete and recreate the header each time, keeping styling/sorting on the header is not possible.

A `clearRows()` method that accepts an `offset` argument or also possibly a range argument like `{start: 2: end: 50}` would be great.

**Comment by theoephraim** [comment]
Added a new sheet.clearRows and added a range arg to sheet.clear as suggested in this PR. Thanks!
- https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-clearrows
- https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-clear

**Pull request closed without merging**
