### PR TITLE
Added function insertDimenion

### PR DESCRIPTION
**Pull request by johnie**
Added the method [insertDimenion](https://developers.google.com/sheets/api/samples/rowcolumn#insert_an_empty_row_or_column) in order to later add the function to insert data at specific position.

### CODE REVIEW

**Comment by HartS** [comment]
@theoephraim any plans to merge this?

**Comment by theoephraim** [comment]
can you undo the linting changes and just add the functionality, tests, and docs.

It's not that I'm totally opposed to changing things, but if I'm going to change the coding style / linting rules, I'd want to change it across the entire codebase at once, with some automated linting tools and checks.

**Comment by johnie** [comment]
@theoephraim Totally agree. Please verify that everything looks good :)

**Comment by sarahkittyy** [comment]
Why was this reverted?

**Comment by theoephraim** [comment]
If I remember correctly, after I merged it, I realized there was some cleanup, docs, housekeeping, etc that needed to be done. Reverted the merge and then did those things and merged back in equivalent changes.

**Pull request merged**
