### PR TITLE
OAuth support

### LINKED ISSUE #425: Implementing OAuth support
Hey @theoephraim,
just forked the repo to start a PR for OAuth support.

Let me brainstorm this with you quickly, there are several options to do this:

Our goal is to provide this library with means to manage the oauth tokens - meaning: we want the library to automatically refresh the token if possible, so that requests just run.
As the end-user will most likely want to store the newly acquired tokens, we also need a callback whenever the token refreshes.

I see mainly two options to implement this, both have their own drawbacks, given the constraints your current implementation provides

- Using google-auth-library - (documentation in README here: https://github.com/googleapis/google-auth-library-nodejs)

You already depend on this library, so we could easily start using the OAuth2Client provided there. The library deals with refreshing the token, notifies whet it does so (through `client.on('tokens', ...)`)
Also allows to generate all the URLs needed for the authenticating user, which is handy. `node-google-spreadsheet` could expose that to make the whole flow very easy. I personally think that this is not strictly required - IMO it's reasonable for this library to say that HOW the oauth credentials are obtained in the first place is out of scope of this library. It just deals with managing tokens the user got from wherever they want.
The major drawback to this solution is that for the auto-refresh to work, request would need to be made through the client itself, e.g. `client.request({ url })`. The whole code around axios (e.g. custom error handling) would get bypassed, and we'd probably need to abstract the whole usage of axios in the library.

- Use Google OAuth Rest API
We don't rely on the google-auth-library, and talk to Google's API directly. It would be our responsibility to manage refreshs of the token. This might mean that we re-implement google-auth-library in parts ourselves. (e.g. pre-emptively refresh the token if we know that it expired, or if we don't know the expiration date refresh the token on a 401 once and retry a request.
This way we could still leave all the axios-based code intact. 

If there was no other code around I'd use google-auth-library directly. As we're building on such a solid foundation already, I'd be in favor of using the Rest API.

The final interface would look something like:

```
useOAuth(
  credentials: {
    clientId: string; // required to refresh the token
    clientSecret: string; // required to refresh the token
    accessToken: string;
    refreshToken: string;
    expiresIn: number; // maybe required, so that we can pre-emptively refresh if need be 
  },
  // onRefreshTokens allows the user to store the new tokens for future use
  onRefreshTokens: (nextTokens: {
    accessToken: string;
    refreshToken: string;
    expiresIn: string
  }) => Promise<void>
```

`What do you think?

### PR DESCRIPTION
**Pull request by LFDM**
Following up on #425 

Minimal implementation of working with Google's OAuth2Client, which manages refreshing access tokens for us automatically.
Contrary to what I outlined in #425, this is IMO a better and simpler way of tackling this, leaving full control in the hands of the user dealing with the oAuth2Client while still getting all the benefits over e.g. using raw access tokens.

Please check out the documentation for more info.

I've successfully tested this in my own application, where I am using this library.
If you agree to these changes, I would also go on and update the typescript types over at DefinitelyTyped.

Closes #425

### CODE REVIEW

**Comment by theoephraim** [comment]
This looks great - I figured it would be easy, but this is even simpler than I thought :)
Just need to add more info to the docs files (not just the readme) - but I will take care of it.

Thanks!!

**Comment by LFDM** [comment]
Ah right, I missed this one here, right? https://github.com/theoephraim/node-google-spreadsheet/blob/master/docs/classes/google-spreadsheet.md

Thanks for helping out!

**Comment by theoephraim** [comment]
yep exactly. Those markdown files are what powers the docs site - https://theoephraim.github.io/node-google-spreadsheet/#/

**Comment by LFDM** [comment]
I see you also expanded on the general documentation, very nice! Thanks for taking care of that - and a happy new year ;)

**Pull request merged**
