### PR TITLE
fix(updateProperties): getFieldMask ignore gridProperties

### PR DESCRIPTION
**Pull request by MathRobin**

### CODE REVIEW

**Comment by theoephraim** [comment]
good catch! and THANK YOU for adding a test as well 🔥 

I'll try to get this merged asap

**Comment by MathRobin** [comment]
you welcome, do you mind if i do multiple dev in same PRs ? with distinct commit, i still have the problem with duplicate headers and I have a very simple solution to manage it

**Comment by theoephraim** [comment]
probably better to split - because the duplicate header stuff isn't quite as clear whereas this is a bugfix

**Comment by MathRobin** [comment]
Hi, when you will be able to merge it please ?

**Pull request merged**
