### PR TITLE
Add sheetsByTitle getter

### PR DESCRIPTION
**Pull request by rubenstolk**

### CODE REVIEW

**Comment by bigomega** [comment]
This is very valuable, thanks. I hope it gets merged soon.

**Comment by rubenstolk** [comment]
Yeah, unfortunately I think this repository has gone stale :) It's a nice project...

**Comment by bigomega** [comment]
cc: @theoephraim

**Comment by cabral-ricardo** [comment]
Oww I would be very grateful for this feature :( @theoephraim :+1: this PR :pray: :pray:

**Comment by theoephraim** [comment]
Hey guys - sorry for the delay. Merging this in shortly.

also fyi - lodash is your friend -- replaced the reduce function with a one-liner `return _.keyBy(this._rawSheets, 'title');`

**Pull request merged**
