### PR TITLE
Adds new auth mode to use the default google auth client

### PR DESCRIPTION
**Pull request by lmartelli**
Works out of the box when deployed on GCP, or using
GOOGLE_APPLICATION_CREDENTIALS env var for local dev.

### CODE REVIEW

**Comment by lmartelli** [comment]
I think this makes `AUTH_MODES.OAUTH` redundant, so I removed it but let `useOAuth2Client` for backward compatibility.

**Comment by suciubogdan** [comment]
+1 for this to get merged if it actually works.

**Comment by horiken4** [comment]
👍

**Comment by horaklukas** [comment]
It would be fantastic to this in the library 😍

**Comment by MacieGx** [comment]
+1

**Comment by theoephraim** [comment]
Thanks for contributing. I was in the middle of a big typescript rewrite that took longer than expected...

I worked this functionality into the new code - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication?id=adc

**Pull request closed without merging**
