### PR TITLE
chore(deps): allow google-auth-library@^9.0.0

### PR DESCRIPTION
**Pull request by ruscon**

### CODE REVIEW

**Comment by el-j** [comment]
before this is merge, override in package.json resolves this:
```
 "overrides": {
    "google-spreadsheet": {
      "google-auth-library": "^9.0.0"
    }
  }
  ```

**Comment by Oreoz** [comment]
Is there anything holding this back? 👀

**Comment by el-j** [comment]
> Is there anything holding this back? 👀

i dont know, maybe a "release" shedule?

**Review by theoephraim — APPROVED** [review]

**Comment by theoephraim** [comment]
merged and published - apologies for the delay!

**Pull request merged**
