### PR TITLE
Add typings

### PR DESCRIPTION
**Pull request by EndBug**
I just thought it would be nice to have typings in this package, so here's a .d.ts file.
It should be ok, take a look at it.

### CODE REVIEW

**Comment by conanak99** [comment]
Hi @EndBug , this typing seems to be really useful. The MR had been active since 1 year and seems like it won't be merge in the near future. 

How about you publish it into another module called `@types/google-spreadsheet`, so people (like me) can make use of that.

**Comment by EndBug** [comment]
@conanak99 Seems like a good idea. In the meantime, you can install this "version" of the package directly from GitHub, from the `pr` branch of my fork ;)

**Comment by EndBug** [comment]
Hey @conanak99, I've looked into the guidelines for DefinitelyTyped and I feel like it's too much work for me, since I'm not even using the package anymore...
If you want to you're welcome to add the package using my definitions, just mind that I made them for a previous version, not the current one, so they may need some little tweaks ;)

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

If you want to do new typings, I'll take a look!

Thanks! 😄

**Pull request closed without merging**
