### PR TITLE
Fix DELETE worksheet url

### PR DESCRIPTION
**Pull request by mg**
Deleting a worksheet is not working, the problem seems to be that the DELETE request is sent to an incorrect URL
`
https://spreadsheets.google.com/feeds/worksheets/key/worksheet_id/private/full
`

the correct being
`
https://spreadsheets.google.com/feeds/worksheets/key/private/full/worksheet_id
`

according to https://developers.google.com/google-apps/spreadsheets/worksheets#delete_a_worksheet

### CODE REVIEW

**Comment by theoephraim** [comment]
Deleting worksheets is used extensively in the tests and it works.
So can you please provide more info about your use case / setup?

Thanks ! :D

**Comment by mg** [comment]
The tests (manage-test.js) call the SpreadsheetWorksheet.del() function, not the GoogleSpreadsheet.removeWorksheet() function. At least Im not finding where that function is being tested.

**Comment by theoephraim** [comment]
Ah! I see. Thanks :)
Can you add a test too and I'll merge it in?

**Comment by mg** [comment]
Will do

**Comment by FGRibreau** [comment]
Hello @mg @theoephraim any updates on this? :)

**Comment by theoephraim** [comment]
Thanks for this. Added some tests too.

**Pull request closed without merging**
